#!/usr/bin/env php
<?php

spl_autoload_register(function ($class) {
    $prefix = 'Cli\\';
    $length = strlen($prefix);
    $baseDirectory = __DIR__ . '/src/';
    if (strncmp($prefix, $class, $length) !== 0) return;
    $relativeClass = substr($class, $length);
    $file = $baseDirectory . str_replace('\\', '/', $relativeClass) . '.php';
    if(file_exists($file)) {
        require $file;
    }
});

const __ROOT__ = __DIR__;

Cli\Main::main($argc, $argv);
